[package]
name = "s3s-aws"
version = "0.0.1"
edition = "2021"
description = "S3 service adapter integrated with aws-sdk-s3"
license = "Apache-2.0"
readme = "../../README.md"
repository = "https://github.com/Nugine/s3s"

[dependencies]
