[project]
name = "s3s"
version = "0.0.0"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "lxml>=5.3.0",
    "requests>=2.32.3",
    "typer>=0.12.5",
]

[tool.ruff]
cache-dir = ".cache/ruff"
