[package]
name = "s3s-codegen"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
heck = "0.4.0"
regex = "1.7.1"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = { version = "1.0.91", features = ["preserve_order"] }
serde_urlencoded = "0.7.1"
