[package]
name = "s3s-codegen"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
heck = "0.4.1"
regex = "1.8.1"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = { version = "1.0.96", features = ["preserve_order"] }
serde_urlencoded = "0.7.1"

[dependencies.codegen-tools]
git = "https://github.com/Nugine/codegen-tools"
rev = "284bd050b9fb763509c3faf7af23b928dea1aea3"
