[package]
name = "s3s"
version = "0.1.0"
edition = "2021"
description = "S3 Service Adapter"
license = "Apache-2.0"
readme = "../../README.md"
repository = "https://github.com/Nugine/s3s"

[dependencies]
arrayvec = "0.7.2"
ascii = { version = "1.1.0", default-features = false }
async-trait = "0.1.61"
atoi = { version = "2.0.0", default-features = false }
base64-simd = "0.8.0"
bytes = "1.3.0"
chrono = { version = "0.4.23", default-features = false }
futures = "0.3.25"
hex-simd = "0.8.0"
hmac = "0.12.1"
httparse = "1.8.0"
hyper = { version = "0.14.23", features = ["stream"] } # TODO(blocking): upgrade to hyper 1.0.0
memchr = "2.5.0"
mime = "0.3.16"
nom = "7.1.2"
quick-xml = { version = "0.27.1", features = ["serialize"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_urlencoded = "0.7.1"
sha2 = "0.10.6"
smallvec = "1.10.0"
thiserror = "1.0.38"
time = { version = "0.3.17", features = ["formatting", "parsing", "macros"] }
tracing = "0.1.37"
transform-stream = "0.2.0"
urlencoding = "2.1.2"

[dev-dependencies]
tokio = { version = "1.24.1", features = ["full"] }
