on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule: # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onschedule
    - cron: '0 0 * * 0' # at midnight of each sunday


name: CI

jobs:
  develop:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain: 
          - 1.66.1 # MSRV
          - stable
          - nightly
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: rustfmt, clippy
      - run: cargo fmt --all -- --check
      - run: cargo clippy -- -D warnings
      - run: cargo test --all-features
