on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule: # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onschedule
    - cron: '0 0 * * 0' # at midnight of each sunday


name: CI

jobs:
  develop:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain: 
          - 1.66.1 # MSRV
          - stable
          - nightly
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: rustfmt, clippy
      - run: cargo fmt --all -- --check
      - run: cargo clippy -- -D warnings
      - run: cargo test --all-features
      - run: |
          ./scripts/codegen.sh
          [[ -z $(git status -s) ]] # Fail if changed. See https://stackoverflow.com/a/9393642

  mint:
    name: E2E (s3s-proxy, mint)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
      - run: docker pull minio/mint:edge
      - run: docker pull minio/minio:latest
      - run: cargo install --path crates/s3s-proxy
      - run: |
          ./scripts/s3s-proxy.sh > /tmp/s3s-proxy.ansi &
          sleep 5s
          ./scripts/mint.sh > /tmp/mint.log
      - run: cat /tmp/s3s-proxy.ansi
      - run: cat /tmp/mint.log
      - run: ./scripts/report-mint.py /tmp/mint/log.json
